sudo: required
services:
  - docker
language: java
jdk: oraclejdk8
dist: trusty

env:
  - COVERAGE=0.5



#steps: echo testing coming soon
#displayname: 'testing coming soon'
before_install:
  - ./gradlew clean jar

stages:
  - test

jobs:
    - stage: test
      name: "Coverage Checks"
      install: echo 'WIP'
      when: on_success
      script:
      - ./gradlew -p ./monolithic/ui check
      - ./gradlew -p ./monolithic/service/cart check
      - ./gradlew -p ./monolithic/service/user check
      - ./gradlew -p ./monolithic/repository/order check
      - ./gradlew -p ./monolithic/repository/cart check
      - ./gradlew -p ./monolithic/repository/product check
      - ./gradlew -p ./monolithic/repository/user check




after_success:
  - set -x -v;
    set -e;
    find . -name jacocoTestReport.csv|xargs cat|awk -F',' '{print $3" "$4" "$4}'












  # Run ANSIBLE checks
  # - ANSIBLE0008: Disabled for use of sudo warnings - to address
  # - ANSIBLE0011: Disabled for all tasks which should be named
  # - ANSIBLE0012: Disabled (should not change if nothings needs doing) - to address
  # - ANSIBLE0013: Disabled - few uses of shell commands - to address
  # find vagrant/provision -name "*.yml" -exec ansible-lint -x ANSIBLE008,ANSIBLE0011,ANSIBLE0012,ANSIBLE0013  {} +
